service: aws-lambda-emp


provider:
 name: aws
 runtime: nodejs14.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: production
 region: ap-southeast-1 # AWS region

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /